Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2021-11, with the labels that each got.

#292 Fix Neuroscope group increments
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
Labels: bug, high priority

#296 GenericDataChunkIterator improvements
  nwb_conversion_tools/utils/genericdatachunkiterator.py
  tests/test_gin.py
Labels: code reduction, performance

#230 Refactored write ephys modules
  nwb_conversion_tools/__init__.py
  nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/sortingtutorialdatainterface.py
  nwb_conversion_tools/utils/__init__.py
  nwb_conversion_tools/utils/basenwbephyswriter.py
  nwb_conversion_tools/utils/basesinwbephyswriter.py
  nwb_conversion_tools/utils/common_writer_tools.py
  nwb_conversion_tools/utils/conversion_tools.py
  nwb_conversion_tools/utils/createextractors.py
  nwb_conversion_tools/utils/ephys_writer.py
  nwb_conversion_tools/utils/neonwbephyswriter.py
  nwb_conversion_tools/utils/nwbephyswriterdatachunkiterator.py
  nwb_conversion_tools/utils/si013nwbephyswriter.py
  nwb_conversion_tools/utils/si090nwbephyswriter.py
  nwb_conversion_tools/utils/spike_interface.py
  requirements-dev.txt
  requirements-rtd.txt
  requirements.txt
  tests/test_si.py
  tests/test_si013.py
  tests/test_si090.py
  tests/test_tools.py
Labels: enhancement

#297 added xml_file_path argument to neuroscope sorting; added docstring; …
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
Labels: bug, documentation

#306 Update basenwbephyswriter.py
  nwb_conversion_tools/utils/basenwbephyswriter.py
Labels: warnings, deprecation fix
