Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2021-07, with the labels that each got.

#201 load metadata from file
  nwb_conversion_tools/utils/metadata.py
  tests/metadata_tests.json
  tests/metadata_tests.yml
  tests/test_json_schema_utils.py
Labels: enhancement

#208 fixing issue 207
  nwb_conversion_tools/utils/spike_interface.py
Labels: bug, high priority

#197 enhanced add_electrical_series
  nwb_conversion_tools/utils/spike_interface.py
  tests/test_si.py
Labels: enhancement

#215 added spikegadgets data interface with new source_schema setting method
  nwb_conversion_tools/datainterfaces/__init__.py
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/__init__.py
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
Labels: enhancement

#216 API docstrings
  docs/api/interfaces.behavior.rst
  docs/api/interfaces.ecephys.rst
  docs/api/interfaces.ophys.rst
  docs/api/interfaces.rst
  docs/api/nwbconverter.rst
  docs/conf.py
  docs/index.rst
  docs/requirements.txt
  nwb_conversion_tools/datainterfaces/__init__.py
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/recordingtutorialdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/sortingtutorialdatainterface.py
  readthedocs.yml
  tests/test_converter.py
  tests/test_interfaces.py
Labels: documentation
