Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2021-12, with the labels that each got.

#300 re-adding UnitProperties to metadata schema in SortingExtractorInterface
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/utils/basenwbephyswriter.py
  tests/test_interfaces.py
Labels: bug, high priority

#301 Fix CellExplorer metadata
  nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
Labels: bug, high priority

#308 Add ophys GIN
  .github/workflows/full-tests-linux.yml
  .github/workflows/full-tests-mac-windows.yml
  .github/workflows/update-testing-data.yml
  tests/test_gin.py
Labels: bug, coverage

#315 deep_dict_update list appending bug fix in default converter
  nwb_conversion_tools/utils/json_schema.py
  tests/test_json_schema_utils.py
Labels: bug, high priority

#311 Remove convert_data() deprecation warning
  nwb_conversion_tools/basedatainterface.py
Labels: documentation, major version, deprecation fix

#316 Make GIN tests run explicitly
  .github/workflows/full-tests-linux.yml
  .github/workflows/full-tests-mac-windows.yml
  .github/workflows/full-tests-mac.yml
  .github/workflows/full-tests-windows.yml
  .github/workflows/partial-tests.yml
  .github/workflows/update-testing-data.yml
  tests/test_gin.py
  tests/test_internals/metadata_tests.json
  tests/test_internals/metadata_tests.yml
  tests/test_internals/test_chunk_iterators.py
  tests/test_internals/test_converter.py
  tests/test_internals/test_interfaces.py
  tests/test_internals/test_json_schema_utils.py
  tests/test_internals/test_si013.py
  tests/test_internals/test_si090.py
  tests/test_internals/test_tools.py
  tests/test_on_data/test_gin.py
Labels: bug, high priority

#313 Add Axona GIN tests
  .github/workflows/full-tests-linux.yml
  .github/workflows/update-testing-data.yml
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/nwbconverter.py
  requirements-full.txt
  tests/test_on_data/test_gin.py
Labels: bug, high priority, coverage

#302 added CED tests to GIN
  .github/workflows/full-tests-linux.yml
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
  requirements-full.txt
  tests/test_internals/test_interfaces.py
Labels: bug, coverage

#321 Update lxml version
  requirements-full.txt
  requirements-minimal.txt
  requirements-rtd.txt
Labels: bug, high priority

#312 Standardize file and folder input arguments
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  tests/test_internals/test_interfaces.py
  tests/test_on_data/test_gin.py
Labels: documentation, major version, organization

#324 recording/sortingextractor interface's writer_class attribute changes
  nwb_conversion_tools/__init__.py
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  nwb_conversion_tools/utils/__init__.py
  nwb_conversion_tools/utils/ephys_writer.py
Labels: bug, high priority

#325 remove channels' slicing in stub
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/utils/basenwbephyswriter.py
  nwb_conversion_tools/utils/basesinwbephyswriter.py
  nwb_conversion_tools/utils/ephys_writer.py
  nwb_conversion_tools/utils/neonwbephyswriter.py
  nwb_conversion_tools/utils/si013nwbephyswriter.py
  nwb_conversion_tools/utils/si090nwbephyswriter.py
  tests/test_internals/test_si013.py
  tests/test_internals/test_si090.py
Labels: high priority, code reduction, performance

#334 Add example YAML conversion specification instance
  tests/test_on_data/GIN_converter_specification.yml
  tests/test_on_data/test_yaml_conversion_specification.py
Labels: enhancement, coverage
