Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2021-08, with the labels that each got.

#224 Add black auto-formatting
  .github/workflows/auto-format.yml
  docs/conf.py
  documentation/conversion_guide.py
  nwb_conversion_tools/auto_qc.py
  nwb_conversion_tools/basedatainterface.py
  nwb_conversion_tools/datainterfaces/__init__.py
  nwb_conversion_tools/datainterfaces/behavior/movie/movie_utils.py
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/brpylib.py
  nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/recordingtutorialdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/sortingtutorialdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/caiman/caimandatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/cnmfe/cnmfedatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/extract/extractdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/sima/simadatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/suite2p/suite2pdatainterface.py
  nwb_conversion_tools/nwbconverter.py
  nwb_conversion_tools/utils/conversion_tools.py
  nwb_conversion_tools/utils/json_schema.py
  nwb_conversion_tools/utils/metadata.py
  nwb_conversion_tools/utils/spike_interface.py
  pyproject.toml
  setup.py
  tests/test_converter.py
  tests/test_interfaces.py
  tests/test_json_schema_utils.py
  tests/test_si.py
  tests/test_tools.py
Labels: documentation

#226 Add speed testing for writing recordings
  nwb_conversion_tools/utils/conversion_tools.py
  tests/test_tools.py
Labels: enhancement

#234 Units provenance
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/utils/spike_interface.py
  tests/test_si.py
Labels: enhancement

#228 attempting to update intandatainterface for new nwbconversiontools api
  .github/workflows/ci-development.yml
  .github/workflows/ci-production.yml
  nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  requirements-dev.txt
  tests/test_gin.py
Labels: bug

#218 DataChunkIterator with specified chunk shape
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/suite2p/suite2pdatainterface.py
  nwb_conversion_tools/utils/conversion_tools.py
  nwb_conversion_tools/utils/genericdatachunkiterator.py
  nwb_conversion_tools/utils/recordingextractordatachunkiterator.py
  nwb_conversion_tools/utils/spike_interface.py
  tests/test_chunk_iterators.py
  tests/test_gin.py
  tests/test_si.py
  tests/test_tools.py
Labels: enhancement

#242 Add Neuroscope GIN
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  tests/test_gin.py
Labels: coverage

#241 Add SpikeGLX GIN
  tests/test_gin.py
Labels: coverage

#238 removing spurious codecov runs; expanding OS coverage
  .github/workflows/ci-development.yml
  .github/workflows/ci-full.yml
  .github/workflows/ci-production.yml
Labels: coverage

#237 Improve file vs folder annotations
  nwb_conversion_tools/__init__.py
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  nwb_conversion_tools/utils/json_schema.py
Labels: code reduction
