Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2021-06, with the labels that each got.

#193 Add load namespaces
  nwb_conversion_tools/auto_qc.py
  nwb_conversion_tools/nwbconverter.py
  requirements-dev.txt
  tests/test_converter.py
  tests/test_si.py
  tutorials/detailed-tutorial.ipynb
  tutorials/simple-tutorial.ipynb
Labels: bug, high priority

#181 add_electrodes changes
  .gitignore
  nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  nwb_conversion_tools/utils/spike_interface.py
  tests/test_si.py
Labels: bug, enhancement

#198 fixes for write_electrodes for properties: group_name and location
  nwb_conversion_tools/utils/spike_interface.py
  requirements-dev.txt
  tests/test_si.py
Labels: bug

#164 added module control for movie interface
  nwb_conversion_tools/datainterfaces/behavior/movie/movie_utils.py
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  tests/test_interfaces.py
Labels: enhancement
