Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2021-09, with the labels that each got.

#245 fix source_data_schema
  nwb_conversion_tools/utils/json_schema.py
Labels: bug, high priority

#247 Adding OpenEphys tests
  requirements-dev.txt
  tests/test_gin.py
Labels: coverage

#248 Add phy gin
  nwb_conversion_tools/datainterfaces/__init__.py
  tests/test_gin.py
Labels: coverage

#249 fixing pep8 violations in json_schema
  nwb_conversion_tools/utils/json_schema.py
Labels: documentation, low priority, warnings

#250 Extend new annotations to SortingInterfaces
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py
  nwb_conversion_tools/utils/json_schema.py
Labels: low priority

#243 adding nsx_to_load as arg for Blackrock files. Fixing tests
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  tests/test_gin.py
Labels: bug

#257 Fix remaining annotations
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/caiman/caimandatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/cnmfe/cnmfedatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/extract/extractdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/hdf5/hdf5datainterface.py
  nwb_conversion_tools/datainterfaces/ophys/sbx/sbxdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/sima/simadatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/suite2p/suite2pdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py
  nwb_conversion_tools/utils/json_schema.py
  nwb_conversion_tools/utils/spike_interface.py
  tests/test_si.py
Labels: documentation, code reduction

#259 Add SpikeInterface .pkl tests
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  tests/test_interfaces.py
Labels: coverage

#256 optional nsx header fields
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
Labels: bug, high priority

#246 Adding SpikeGadgets tests
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  nwb_conversion_tools/utils/json_schema.py
  requirements-dev.txt
  tests/test_gin.py
Labels: bug, coverage

#252 Fix sorting interface
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  tests/test_interfaces.py
Labels: bug, coverage

#253 Add tutorial tests
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/recordingtutorialdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/sortingtutorialdatainterface.py
  tests/test_interfaces.py
  tutorials/detailed-tutorial.ipynb
  tutorials/simple-tutorial.ipynb
Labels: bug, documentation, coverage

#268 generalized get_source_schema() across all interfaces
  nwb_conversion_tools/basedatainterface.py
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
Labels: code reduction
