Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2022-03, with the labels that each got.

#406 Refactor add electrodes
  nwb_conversion_tools/utils/spike_interface.py
  requirements-full.txt
  requirements-minimal.txt
Labels: code reduction

#405 adding movie data chunk iterator
  nwb_conversion_tools/datainterfaces/behavior/movie/movie_utils.py
  tests/test_internals/test_movie_utils.py
Labels: enhancement

#409 Updated installation documentation
  README.md
Labels: documentation

#411 Reorganize tools
  nwb_conversion_tools/__init__.py
  nwb_conversion_tools/basedatainterface.py
  nwb_conversion_tools/datainterfaces/behavior/movie/movie_utils.py
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  nwb_conversion_tools/datainterfaces/ecephys/tutorial/recordingtutorialdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/caiman/caimandatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/cnmfe/cnmfedatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/extract/extractdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/hdf5/hdf5datainterface.py
  nwb_conversion_tools/datainterfaces/ophys/sbx/sbxdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/sima/simadatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/suite2p/suite2pdatainterface.py
  nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py
  nwb_conversion_tools/nwbconverter.py
  nwb_conversion_tools/tools/__init__.py
  nwb_conversion_tools/tools/nwb_helpers.py
  nwb_conversion_tools/tools/roiextractors/__init__.py
  nwb_conversion_tools/tools/roiextractors/roiextractors.py
  nwb_conversion_tools/tools/spikeinterface/__init__.py
  nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
  nwb_conversion_tools/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
  nwb_conversion_tools/tools/yaml_conversion_specification/__init__.py
  nwb_conversion_tools/tools/yaml_conversion_specification/yaml_conversion_specification.py
  nwb_conversion_tools/utils/__init__.py
  nwb_conversion_tools/utils/dict.py
  nwb_conversion_tools/utils/json_schema.py
  nwb_conversion_tools/utils/types.py
  requirements-full.txt
  requirements-minimal.txt
  tests/test_internals/test_converter.py
  tests/test_internals/test_json_schema_utils.py
  tests/test_internals/test_movie_interface.py
  tests/test_internals/test_movie_utils.py
  tests/test_internals/test_schemas.py
  tests/test_internals/test_si.py
  tests/test_internals/test_tools.py
  tests/test_on_data/test_YAML_conversion_specification.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_gin_ophys.py
Labels: high priority, organization

#417 Channel name testing suggestions
  tests/test_internals/test_si.py
Labels: performance, organization

#418 removed soft import logic for parameterized
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_gin_ophys.py
Labels: dependencies

#433 Update tutorials and add them to the documentation
  docs/data_interface.rst
  docs/index.rst
  docs/tutorials.rst
  docs/user_guide.rst
  tutorials/detailed-tutorial.ipynb
  tutorials/simple-tutorial.ipynb
Labels: documentation

#432 Update neuroscope interface to use spike interface
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscope_utils.py
  nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  requirements-full.txt
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement

#436 Enabled progress bar option for SIRecordingIterator
  nwb_conversion_tools/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
Labels: enhancement
