Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2022-02, with the labels that each got.

#391 Fix sudden install issues
  .github/workflows/testing-linux.yml
  .github/workflows/testing-mac.yml
  .github/workflows/testing-windows.yml
Labels: bug, high priority

#352 Adding reading matlab new format capabilities to the CellExplorerInterface
  .github/workflows/testing-linux.yml
  .github/workflows/update-testing-data.yml
  nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  requirements-full.txt
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, high priority, dependencies, coverage

#344 Run NWB Conversion from YAML specification
  nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  nwb_conversion_tools/nwbconverter.py
  nwb_conversion_tools/utils/conversion_tools.py
  nwb_conversion_tools/utils/nwbfile_tools.py
  nwb_conversion_tools/utils/spike_interface.py
  requirements-minimal.txt
  tests/test_internals/test_tools.py
  tests/test_on_data/conversion_specifications/GIN_conversion_specification.yml
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_missing_nwbfile_names.yml
  tests/test_on_data/conversion_specifications/GIN_conversion_specification_no_nwbfile_name_or_other_metadata.yml
  tests/test_on_data/test.nwb
  tests/test_on_data/test_YAML_conversion_specification.py
Labels: enhancement, organization

#396 Python 3.9 compatibility
  .github/workflows/testing-linux.yml
  .github/workflows/testing-mac.yml
  .github/workflows/testing-windows.yml
  requirements-full.txt
Labels: dependencies

#387 Make session_start_time required
  nwb_conversion_tools/utils/nwbfile_tools.py
  nwb_conversion_tools/utils/spike_interface.py
  tests/test_internals/test_converter.py
  tests/test_internals/test_interfaces.py
  tests/test_internals/test_movie_interface.py
  tests/test_internals/test_si.py
  tests/test_internals/test_tools.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_gin_ophys.py
Labels: documentation

#397 Move ophys write functions from roiextractors
  nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
  nwb_conversion_tools/tools/roiextractors.py
  requirements-full.txt
  requirements-minimal.txt
  tests/test_on_data/test_gin_ophys.py
Labels: organization

#365 Move auto_qc to nwbinspector
  nwb_conversion_tools/auto_qc.py
  nwb_conversion_tools/utils/conversion_tools.py
Labels: documentation, organization

#408 Provide a pip installable testing suite
  make_env_testing.yml
  requirements-full.txt
  setup.py
Labels: enhancement, discussion

#407 add common configuration file for testing data
  .gitignore
  README.md
  tests/test_on_data/gin_test_config.json
  tests/test_on_data/test_YAML_conversion_specification.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_gin_ophys.py
Labels: enhancement, discussion
