Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2022-06, with the labels that each got.

#538 Fix metadata combination of imaging and segmentation interfaces
  src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
  tests/test_on_data/test_metadata_combinations.py
Labels: bug, high priority, testing

#536 Refactor of `add_two_photon_series`
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
Labels: refactoring

#543 Unit test `roiextractors.py` module `add device`
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: high priority, testing, refactoring

#541 Added check to avoid adding roi response series with only 0 values
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
Labels: high priority

#546 Unit test `add_two_photon_series` in the `roiextractors.py` module
  requirements-full.txt
  requirements-minimal.txt
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
  src/nwb_conversion_tools/utils/checks.py
  tests/test_internals/test_roi_extractors_module.py
Labels: high priority, testing

#542 [Refactoring/Enhancement] Pad buffering in GenericDataChunkIterator
  src/nwb_conversion_tools/tools/hdmf.py
  tests/test_internals/test_hdmf.py
Labels: enhancement

#548 Added stubbing for write imaging
  src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
Labels: enhancement

#565 Update conversion gallery to new parameters
  docs/conversion_examples_gallery/sorting/cellexplorer.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
  tests/test_internals/test_si.py
Labels: warnings, deprecation fix

#563 Add spikeinterface support to `BlackrockRecordingExtractorInterface`
  src/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, testing

#567 Add spikeinterface support to `PhySortingInterface`
  src/nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, testing

#558 Refactor intan data interface
  src/nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: code reduction

#574 Added timezone to session start time in add_units_table tests
  tests/test_internals/test_si.py
Labels: warnings

#555 Synchronize with latest changes in roiextractors
  requirements-full.txt
  requirements-minimal.txt
  src/nwb_conversion_tools/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/suite2p/suite2pdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py
  tests/test_internals/test_roi_extractors_module.py
  tests/test_on_data/test_gin_ophys.py
  tests/test_on_data/test_metadata/test_scanimage_metadata.py
  tests/test_on_data/test_metadata_combinations.py
Labels: dependencies, testing

#562 Added docstring and refactor metadata to `IntanRecordingInterface`
  src/nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
Labels: documentation, testing, refactoring

#581 Gin test for scan image
  tests/test_on_data/test_gin_ophys.py
Labels: testing
