Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2022-07, with the labels that each got.

#573 Add spikeinterface support for `SpikeGadgetsRecordingInterface`
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  requirements-full.txt
  src/nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, testing

#576 Remove optional typing in neuroscope
  src/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
Labels: low priority

#577 Refactor neuralynx before adding support for spikeinterface
  src/nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
Labels: refactoring

#564 Add spikeinterface support to `OpenEphysRecordingExtractorInterface`
  docs/conversion_examples_gallery/recording/openephys.rst
  requirements-full.txt
  requirements-minimal.txt
  src/nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, testing

#578 Add spike interface support to neuralynx
  src/nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_metadata/test_neuralynx_metadata.py
Labels: enhancement, testing

#587 Update spikeextractors version to latest
  requirements-full.txt
  requirements-minimal.txt
Labels: dependencies, warnings

#586 Scan image interface to use proper roiextractor
  .github/workflows/testing.yml
  requirements-full.txt
  src/nwb_conversion_tools/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
Labels: enhancement

#580 Refactor metadata extraction for `ScanImageImagingInterface`
  .github/workflows/testing.yml
  requirements-full.txt
  src/nwb_conversion_tools/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
  tests/test_on_data/test_gin_ophys.py
  tests/test_on_data/test_metadata/test_scanimage_metadata.py
Labels: warnings, testing, refactoring

#585 Add optical physiology interfaces to conversion gallery I
  .github/workflows/testing.yml
  docs/api/interfaces.ophys.rst
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/imaging/hdf5imaging.rst
  docs/conversion_examples_gallery/imaging/scanbox.rst
  docs/conversion_examples_gallery/imaging/scanimage.rst
  docs/conversion_examples_gallery/imaging/tiff.rst
  docs/index.rst
  src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/hdf5/hdf5datainterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/sbx/sbxdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
Labels: documentation

#604 [Testing]: Bypass git-annex install if unneeded
  .github/workflows/testing.yml
Labels: bug, testing

#601 Refactor write segmentation I
  src/nwb_conversion_tools/tools/roiextractors/__init__.py
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: testing, refactoring

#602 Refactor write segmentation II (use `add_devices`)
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
Labels: testing, refactoring

#603 Refactor write segmentation III (add summary images)
  requirements-full.txt
  requirements-minimal.txt
  src/nwb_conversion_tools/tools/roiextractors/__init__.py
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
  tests/test_internals/test_roi_extractors_module.py
Labels: testing, refactoring
