Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2022-05, with the labels that each got.

#485 Change default behavior of setting property name as description in electrode table
  src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
Labels: warnings, refactoring

#492 [Feature] Add automatic dandi upload
  .github/workflows/testing.yml
  src/nwb_conversion_tools/tools/data_transfers.py
  tests/test_internals/test_tools.py
Labels: enhancement, high priority

#477 Add device metadata for spikeglx interface
  src/nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  tests/test_on_data/test_metadata/test_spikeglx_metadata.py
Labels: enhancement

#496 Make nwbfile argument optional in `run_conversion` for recording and sorting interfaces
  requirements-full.txt
  requirements-minimal.txt
  src/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
Labels: enhancement

#494 [Feature] Automated globus transfer
  src/nwb_conversion_tools/tools/data_transfers.py
  tests/test_internals/test_tools.py
Labels: enhancement, high priority

#498 Documentation: Pip installable environment and build instructions
  .readthedocs.yaml
  README.md
  requirements-rtd.txt
  setup.py
Labels: documentation, high priority, dependencies

#503 Allow `BlackrockRecordingExtractorInterface` to do `run_conversion` with no nwbfile
  src/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
Labels: enhancement, high priority, code reduction

#505 Allow sorting interface to `run_conversion` without a nwbfile
  src/nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
Labels: enhancement, high priority

#506 Allow sorting interface to run_conversion without a nwbfile II
  src/nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
Labels: enhancement, high priority

#513 [Bug] Only run DANDI test if key is present
  tests/test_internals/test_tools.py
Labels: bug

#514 [Bug] Trying to fix datalad for new cache
  .github/workflows/testing.yml
Labels: bug

#512 [Feature] context helper for appending/making NWBFiles
  src/nwb_conversion_tools/tools/nwb_helpers.py
  tests/test_internals/test_tools.py
Labels: enhancement

#520 [Bug] remove default session_start_time
  src/nwb_conversion_tools/tools/neo/neo.py
Labels: bug

#519 [Refactor] automated dandi upload improvements
  src/nwb_conversion_tools/tools/data_transfers.py
  tests/test_internals/test_tools.py
Labels: refactoring

#495 Conversion examples in the documentation and docstrings
  codecov.yml
  docs/__init__.py
  docs/api/interfaces.ecephys.rst
  docs/api/tools.rst
  docs/api/tools.yaml_to_nwb_conversion.rst
  docs/conf.py
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/__init__.py
  docs/conversion_examples_gallery/conftest.py
  docs/conversion_examples_gallery/recording/axona.rst
  docs/conversion_examples_gallery/recording/blackrock.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/neuroscope.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/conversion_examples_gallery/recording/spikeglx.rst
  docs/conversion_examples_gallery/sorting/cellexplorer.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
  docs/developer_guide.rst
  docs/developer_guide/build_data_interface.rst
  docs/developer_guide/project_structure.rst
  docs/index.rst
  pyproject.toml
  requirements-rtd.txt
  src/nwb_conversion_tools/datainterfaces/ecephys/kilosort/kilosortdatainterface.py
Labels: documentation, enhancement, high priority, testing

#521 Refactor test movie interface for CI bug
  tests/test_internals/test_movie_interface.py
Labels: bug, low priority, testing

#522 Small refactor of movie interface
  src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
Labels: low priority, refactoring

#516 [Refactor] run/write kwargs standardization
  docs/conversion_examples_gallery/recording/axona.rst
  docs/conversion_examples_gallery/recording/blackrock.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/neuroscope.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/conversion_examples_gallery/recording/spikeglx.rst
  requirements-rtd.txt
  src/nwb_conversion_tools/basedatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
  src/nwb_conversion_tools/datainterfaces/icephys/baseicephysinterface.py
  src/nwb_conversion_tools/nwbconverter.py
  src/nwb_conversion_tools/tools/nwb_helpers.py
  src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_interfaces.py
  tests/test_internals/test_si.py
  tests/test_internals/test_tools.py
Labels: code reduction, refactoring

#526 [Refactor] standardize LFP conversion kwargs
  src/nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
Labels: code reduction, refactoring

#524 [Refactor] Standardize conversion kwargs ophys
  src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
Labels: code reduction, refactoring

#525 [Refactor] standardize sorting interface kwargs
  docs/conversion_examples_gallery/sorting/cellexplorer.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
  src/nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/kilosort/kilosortdatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/tutorial/sortingtutorialdatainterface.py
  src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_interfaces.py
Labels: code reduction, refactoring

#527 Add timestamps for MovieDataInterface
  src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  src/nwb_conversion_tools/utils/__init__.py
  src/nwb_conversion_tools/utils/checks.py
  tests/test_internals/test_movie_interface.py
  tests/test_internals/test_utils.py
Labels: enhancement, high priority

#529 [CI] swap to pre commit bot instead of actions
  .github/CODE_OF_CONDUCT.rst
  .github/workflows/auto-format.yml
  .github/workflows/testing.yml
  .github/workflows/update-caches.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  CITATION.cff
  README.md
  docs/_static/css/custom.css
  docs/api/tools.roiextractors.rst
  docs/api/tools.rst
  docs/api/tools.spikeinterface.rst
  docs/api/tools.yaml_to_nwb_conversion.rst
  docs/api/utils.rst
  docs/conversion_example_gallery.rst
  docs/conversion_examples_gallery/recording/axona.rst
  docs/conversion_examples_gallery/recording/blackrock.rst
  docs/conversion_examples_gallery/recording/intan.rst
  docs/conversion_examples_gallery/recording/neuralynx.rst
  docs/conversion_examples_gallery/recording/neuroscope.rst
  docs/conversion_examples_gallery/recording/openephys.rst
  docs/conversion_examples_gallery/recording/spikegadgets.rst
  docs/conversion_examples_gallery/recording/spikeglx.rst
  docs/conversion_examples_gallery/sorting/cellexplorer.rst
  docs/conversion_examples_gallery/sorting/kilosort.rst
  docs/conversion_examples_gallery/sorting/neuroscope.rst
  docs/conversion_examples_gallery/sorting/phy.rst
  docs/developer_guide/build_data_interface.rst
  docs/img/nwb_conversion_tools_uml.svg
  docs/index.rst
  docs/tutorials.rst
  docs/user_guide.rst
  documentation/conversion_guide.py
  documentation/conversion_tools_structure.md
  documentation/converting_data_to_nwb.md
  make_env.yml
  make_env_testing.yml
  src/nwb_conversion_tools/schemas/metadata_schema.json
  src/nwb_conversion_tools/schemas/source_example.json
  src/nwb_conversion_tools/schemas/yaml_conversion_specification_schema.json
  tests/test_internals/metadata_tests.json
Labels: testing

#532 Small refactor of `test_gin_behavior` to pin new CI error
  .github/workflows/testing.yml
  requirements-full.txt
  requirements-minimal.txt
  src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
  tests/test_on_data/test_gin_behavior.py
Labels: bug, testing

#531 Add `.yaml` to accepted yaml extensions in `load_dict_from_file` function
  src/nwb_conversion_tools/utils/dict.py
  tests/test_internals/metadata_tests.yaml
  tests/test_internals/test_json_schema_utils.py
Labels: enhancement, low priority

#535 Update default parameters for ophys
  src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
  tests/test_on_data/test_gin_ophys.py
  tests/test_on_data/test_metadata/test_scanimage_metadata.py
Labels: high priority
