Repository catalystneuro/nwb-conversion-tools, pull requests merged in 2022-04, with the labels that each got.

#457 [Feature]: Helper functions for inverse f-string YAML specification
  docs/api/utils.rst
  docs/index.rst
  src/nwb_conversion_tools/utils/__init__.py
  src/nwb_conversion_tools/utils/globbing.py
  tests/test_internals/test_globbing_utils.py
Labels: enhancement

#458 [Testing]: Add NeuroscopeSorting data tests
  .github/workflows/testing.yml
  src/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: coverage

#460 Not overwriting channel name if recording object has the property
  src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
  tests/test_on_data/test_gin_ecephys.py
Labels: bug, enhancement, warnings

#459 Warning reduction : remove numpy type warnings.
  requirements-full.txt
  src/nwb_conversion_tools/utils/types.py
  tests/test_internals/test_movie_interface.py
  tests/test_on_data/test_gin_behavior.py
Labels: warnings, deprecation fix

#464 Memmap data chunk iterator
  src/nwb_conversion_tools/tools/hdmf.py
  tests/test_internals/test_tools/test_hdmf.py
Labels: enhancement

#465 Update spikelgx to use spikeinterface II proposal
  .github/workflows/testing.yml
  .github/workflows/update-caches.yml
  src/nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglx_utils.py
  src/nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
  tests/test_on_data/test_gin_ecephys.py
  tests/test_on_data/test_metadata/test_neuroscope_metadata.py
  tests/test_on_data/test_metadata/test_spikelgx_metadata.py
Labels: enhancement, high priority

#470 [Bug]: add keywords to base NWB metadata schema
  src/nwb_conversion_tools/utils/json_schema.py
Labels: bug, high priority

#469 [Workflow]: Automatic adding of Issues/PRs to Dashboard
  .github/workflows/add-to-dashboard.yml
Labels: enhancement

#474 add default values to run_conversion
  src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
  src/nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py
Labels: enhancement

#475 [Feature]: add verbosity control to main converter
  src/nwb_conversion_tools/nwbconverter.py
Labels: enhancement

#481 Added empty dict as root value to recursion in `dict_deep_update` to solve warnings.
  src/nwb_conversion_tools/utils/dict.py
Labels: warnings

#487 Add kilosort data interface
  src/nwb_conversion_tools/datainterfaces/__init__.py
  src/nwb_conversion_tools/datainterfaces/ecephys/kilo/__init__.py
  src/nwb_conversion_tools/datainterfaces/ecephys/kilo/kilodatainterface.py
  src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
  tests/test_on_data/test_gin_ecephys.py
Labels: enhancement, high priority

#488 [Feature] globus-specific size retrieval helper
  src/nwb_conversion_tools/tools/data_transfers.py
  tests/test_internals/test_tools.py
Labels: enhancement

#484 Add_units_table also adds unit_name
  src/nwb_conversion_tools/tools/spikeinterface/__init__.py
  src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
  tests/test_internals/test_si.py
Labels: medium priority

#489 [Feature] Add s3 cost equation
  src/nwb_conversion_tools/tools/data_transfers.py
  tests/test_internals/test_tools.py
Labels: enhancement
